# Generated by vCreatek EEP
# State stored in Terraform Cloud — local execution on self-hosted runner

terraform {
  backend "remote" {
    organization = "vcreatek-eep"

    workspaces {
      name = "${{ values.owner_name }}-${{ values.vm_name }}"
    }
  }
}