# Generated by vCreatek EEP
# VM: ${{ values.vm_name }} | Team: ${{ values.owner_name }}
# Do not edit manually — use EEP to update

module "vm" {
  source = "git::https://github.com/vcreatek-demo/vcreatek-infrastructure.git//modules/vcreatek-vm?ref=main"

  proxmox_api_url      = "https://10.10.1.63:8006/api2/json"
  proxmox_token_id     = var.proxmox_token_id
  proxmox_token_secret = var.proxmox_token_secret

  vm_name        = var.vm_name
  vm_description = var.vm_description
  owner_team     = var.owner_team
  environment    = var.environment
  vm_ip          = var.vm_ip
  vm_cores       = var.vm_cores
  vm_memory      = var.vm_memory
  vm_disk_size   = var.vm_disk_size
  vm_user        = var.vm_user
  vm_password    = var.vm_password
}

variable "proxmox_token_id"     { sensitive = true }
variable "proxmox_token_secret" { sensitive = true }
variable "vm_password"          { sensitive = true }
variable "vm_ip"                {}
variable "vm_name"              {}
variable "vm_description"       {}
variable "owner_team"           {}
variable "environment"          { default = "development" }
variable "vm_cores"             { default = 2 }
variable "vm_memory"            { default = 2048 }
variable "vm_disk_size"         { default = 20 }
variable "vm_user"              { default = "vcreatek" }

output "ssh_command" { value = module.vm.ssh_command }
output "vm_ip"       { value = module.vm.vm_ip }
output "vm_id"       { value = module.vm.vm_id }