# Generated by vCreatek EEP
# VM: ${{ values.vm_name }} | Team: ${{ values.owner_name }}
# To update this VM — raise a PR modifying this file

vm_name        = "${{ values.vm_name }}"
vm_description = "${{ values.vm_description }}"
owner_team     = "${{ values.owner_name }}"
environment    = "${{ values.environment }}"
vm_cores       = ${{ values.vm_cores }}
vm_memory      = ${{ values.vm_memory }}
vm_disk_size   = ${{ values.vm_disk_size }}
vm_user        = "${{ values.vm_user }}"
